// BYOK_MASTER_KEY decoding + global key-version pin.
//
// The env var is a base64-encoded 32-byte random value. Generated by the
// operator via `openssl rand -base64 32` (see plan/phases/phase_26 brief).
// When unset / wrong-length, the rest of the BYOK surface treats this as
// "BYOK not enabled": settings page renders a one-liner, /api/byok/*
// returns 503. The rest of the app is unaffected.
//
// Pure / synchronous; the env read is the only side effect.

export const BYOK_KEY_VERSION = 1
export const MASTER_KEY_BYTES = 32
export const IV_BYTES = 12

export function getMasterKey(
  source: Record<string, string | undefined> = process.env,
): Buffer | null {
  const raw = source.BYOK_MASTER_KEY
  if (typeof raw !== 'string') return null
  const trimmed = raw.trim()
  if (trimmed.length === 0) return null
  let decoded: Buffer
  try {
    decoded = Buffer.from(trimmed, 'base64')
  } catch {
    return null
  }
  if (decoded.length !== MASTER_KEY_BYTES) return null
  // Round-trip guard: Buffer.from('not-base64', 'base64') silently
  // produces garbage of unpredictable length, so the strict-equality
  // check above already filters most junk. But a string that happens
  // to decode to 32 bytes despite not being valid base64 would slip
  // through; re-encode and compare to catch that case.
  const reencoded = decoded.toString('base64')
  if (reencoded.replace(/=+$/, '') !== trimmed.replace(/=+$/, '')) {
    return null
  }
  return decoded
}
